<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\MetaCrudFosis.Shared.Modern\MetaCrudFosis.Shared.Modern.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Views\Log\" />
    <Folder Include="Views\Producto\" />
    <Folder Include="Views\Shared\Components\NavEntidades\" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
