<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="wwwroot\css\modern-theme.css">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>modern-theme.Designer.cs</LastGenOutput>
    </Content>
    <Content Update="wwwroot\css\modern-theme.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>modern-theme.css</DependentUpon>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Views\Shared\" />
  </ItemGroup>



</Project>
